TooNovel/TooNovel-BE

src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #17 
- 회원 탈퇴 + RefreshToken 삭제 처리
<br>
- `UserController` @DeleteMapping("/me")
- `UserService` deleteUser() 메소드
<br>
- 이전 작업에서 빠졌던 탈퇴 기능 구현하였습니다. 
- RefreshToken이 없는 예외는 의도적으로 발생시키지 않았습니다. 
- Controller에서 ~~~Profile   형태로 이름을 통일할까 하다가, 일단은 그대로 뒀습니다.
deleteMyProfile, getMyProfile, registerMyProfile 이런 식으로 네이밍 통일하는 게 좋을까요? 
<br>
=> [FEAT] User 탈퇴 기능 구현

src/main/java/com/yju/toonovel/domain/novel/exception/NovelNotFoundException.java, src/main/java/com/yju/toonovel/domain/novel/exception/PlatformNotFoundException.java, src/main/java/com/yju/toonovel/domain/user/exception/InvalidUserException.java, src/main/java/com/yju/toonovel/domain/user/exception/UserNotFoundException.java, src/main/java/com/yju/toonovel/global/error/ErrorResponse.java, src/main/java/com/yju/toonovel/global/error/GlobalExceptionHandler.java, src/main/java/com/yju/toonovel/global/error/exception/BusinessException.java, src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredRefreshTokenException.java, src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredTokenException.java, src/main/java/com/yju/toonovel/global/security/jwt/exception/InvalidTokenException.java, src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationEntryPoint.java
- resolve #23 
- `Business Exception`을 구현하여, `Service` 레이어에서 발생한 에러들의 원인을 제대로 반환하도록 하였습니다.
<br>
- `Business Exception` 구현
- `ErrorResponse` 수정
- `GlobalExceptionHandler` 수정
- 이전에 구현된 `Custom Exception` 수정
<br>
- 이후에 작업하시는 도메인, 기능들에 대해서 필요한 예외가 있다면 구현하여 작업해주시면 됩니다.
- 이전에 주석 처리했던 `handleInternalServerException`의 주석 처리를 해제했습니다.               
<br>
=> [FEAT] Business Exception 처리 구현

src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java, src/main/java/com/yju/toonovel/domain/novel/entity/Genre.java, src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java, src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java, src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #25 
- 소설 검색 기능 구현
- 조회 기능과 통합
- 정렬 기준 변경(최신순)
<br>
- `Genre`
- `@JsonValue`, `@JsonCreator` 사용하여 직렬화 하였습니다.
- `Novel`
- 설명과 이미지의 길이를 지정하였습니다.
- `findAllNovel` 로 검색, 조회 기능을 통합하였습니다.
- 정렬을 최신순으로 변경하였습니다. 이후 요구 조건이 늘어나면 Sort 방식을 추가하겠습니다.
<br>
- `Genre` 파일의 수정으로 이후 `Review` 도메인 기능 수정이 필요합니다.          
<br>
=> [FEAT] 소설 검색 기능 구현 및 조회 기능 수정

src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java, src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/recommend/controller/RecommendController.java, src/main/java/com/yju/toonovel/domain/recommend/service/RecommendService.java, src/main/java/com/yju/toonovel/global/config/WebConfig.java, src/main/resources/application.yaml
- resolve #28 
- FE <-> BE <-> ML 과정을 거칩니다.
<br>
- 서버 주소를 환경 변수로 관리
- 이전 코드 리뷰에서 이야기했던 부분을 반영하였습니다.
- 추천 기능 구현
- 실제 추천은 ML서버에서 이루어지고, BE서버에서는 받아온 추천 목록을 통해 소설 목록을 조회하고 반환합니다.
<br>
-  [RestTemplate Deprecated?](https://velog.io/@dailylifecoding/Spring-RestTemplate-wont-Deprecate)
- [Deploy BERT for Sentiment Analsysi with FastAPI](https://github.com/curiousily/Deploy-BERT-for-Sentiment-Analysis-with-FastAPI)
- 위 두 링크 읽어보고 코드 작성하였습니다.
<br>
=> [FEAT] 추천 시스템 서버와 연결

src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #37 
- FE에서 좋아요 한 작품 리스트를 페이지네이션 하는 과정에서 `likeNovelId`가 필요한 것을 인지하여 추가
<br>
- `NovelPaginationResponseDto` 분리
- `NovelPaginationResponseDto`
- `LikeNovelPaginationResponseDto`
- 반환 정보에 LikeNovel의 id값도 포함
<br>
- 이전에 꼼꼼하게 신경을 썼어야 하는데 죄송합니다.  더 수정할 사항 있으면 말씀해주세요                  
<br>
=> [REFACTOR] '좋아요' 한 작품 리스트 반환 수정

src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java, src/main/java/com/yju/toonovel/domain/recommend/controller/RecommendController.java, src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/global/common/Sort.java
- resolve #42 
- FE 요청에 따라 정렬 기준을 추가하고, 이후에 추가하기 편하게 개선하였습니다.
- ResponseStatus를 반환하도록 수정하고, Postman 으로 API 명세를 공유하였습니다.
<br>
- `PostController`를 제외한 모든 Controller에 `@ResponseStatus`를 추가하였습니다.
- Get : 200
- Put, Patch, Post : 201
- Delete : 204
- `Sort` 를 `Enum` 클래스로 관리하도록 합니다.
- 현재는 최신 순, 오래된 순, 인기 리뷰 순을 추가한 상태입니다.
각 작업하시면서 추가하여 사용하시면 되겠습니다.
<br>
- 사소한 변경이지만, 우선 작업해서 반영해 두면 뒤 작업이 편할 것 같아서 작은 단위로 이슈를 만들고 PR을 올렸습니다.
- 기존 조회 `Dto`에 `Sort`를 추가하고, 각 조회에 반영하시면 될 것 같습니다.        
<br>
=> [FEAT] API 명세서 작성을 위한 수정

src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java, src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java, src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryCustom.java, src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
- resolve #41 
<br>
- 리뷰 전체 조회 할 때, 정렬기준 및 장르별 조회를 위한 동적쿼리 기능 구현
-  ReviewPaginationRequestDto 통해 숫자 페이징 및 동적쿼리에서 사용할 정렬기준, 장르를 받습니다.
- getOrderSpecifiers메서드를 통해 사용자가 url에 보내준 정렬 기준을 가져와 order by해줍니다.
<br>
- 하나의 작품에 해당되는 리뷰를 조회할 때 사용되는 dto와 전체 리뷰 조회할 때 사용되는 dto가 다르다 보니, 일단은 주석 처리 해두었습니다
- 만약 하나의 작품에 해당되는 리뷰를 조회한다면, 중복 코드 제거를 위해 따로 빼두었던 reviewSelect를 하나의 작품에 해당되는 리뷰를 조회하는 dto를 사용할 수 있도록 하나 더 만들어야 하는데 이게 맞는 것일지, 아니면 따로 빼두지 않고 메서드 안에다가 원래대로 넣을지 고민이 됩니다.           
<br>
=> [REFACTOR] Review 도메인 리팩토링

src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java, src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/review/entity/Review.java, src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java, src/main/java/com/yju/toonovel/global/common/Sort.java
- resolve #45 
- 이전에 해당 작품에 달린 Review의 평균 값(평점)을 알 수 있는 기능을 추가하지 않았었는데, 이번에 추가하였습니다.
단건 조회나 전체 조회에서 작품 별 평점을 확인 할 수 있도록 하고, 평점을 기준으로(높은 순) 조회하는 기능을 추가하였습니다.
<br>
- 모든 ResponseDto에 grade(평점)을 반환하도록 추가 하였습니다.
- 전체 조회 요청 시 Sort기준으로 평점 순을 요청할 수 있도록 하였습니다.
- `sort=NOVEL_GRADE_DESC`
- 지정하지 않으면 최신 작품 순으로 정렬하도록 하였습니다.
<br>
- `Review` 엔티티의 평점 부분을 notnull 처리 하였습니다. 
- ReviewGrade가 int형이라 Novel의 grade도 Integer로 하였습니다.
- 주말 동안의 작업으로 기존에 FE에서 작업한 부분에서 조금 변경이 필요합니다.. 
<br>
=> [FEAT] Novel 도메인 기능 추가

build.gradle, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/dto/UserRegisterRequestDto.java, src/main/java/com/yju/toonovel/domain/user/entity/User.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #55 
- User 도메인에 한해서 validation 작성
- 회원 탈퇴 - Soft Delete 로 변경
<br>
- 회원 가입 요청에 사용되는 API가 회원 정보 수정과 현재 같다고 생각되어 메소드 이름을 변경하고, API 주소를 변경하였습니다.
- `/register` -> `/me`
- 메소드 이름을 `updateUser`로 일괄 변경
- 기존에는 `regiser`,`userRegister` 가 혼용
- `UserRegisterRequestDto` 에 validation 작업
- 회원 탈퇴 정책 수정
- 과거 구현한 회원 탈퇴 기능은 작동하지 않아 수정이 필요했습니다.
-  Soft Delete로 변경하였습니다.
<br>
- 코드나 정책 관련해서 의견 있으시면 말씀해주세요!!      
- 이미지 업로드 기능 추가 이후에, 회원 정보 수정 기능이 다시 분리되거나 변경될 가능성이 있습니다.                   
<br>
=> [FEAT] User 도메인 validation 추가

src/main/java/com/yju/toonovel/domain/comment/entity/Comment.java, src/main/java/com/yju/toonovel/domain/comment/entity/LikeComment.java, src/main/java/com/yju/toonovel/domain/review/entity/LikeReview.java, src/main/java/com/yju/toonovel/domain/review/service/LikeReviewService.java
- resolve #58 
<br>
- 댓글 삭제 시 댓글 좋아요에 있던 관계 때문에 삭제 되지 않은 버그 -> ondelete어노테이션 활용해 삭제 되도록 구현
- 리뷰 좋아요 클릭시 좋아요 카운트 증가되지 않은 버그 -> 좋아요 증가하는 메서드 구현
<br>
- 추후 ondelete 어노테이션은 더 바람직하게 삭제 될 수 있도록 수정해야 할 것 같습니다.                   
<br>
=> [BUG] Comment, Reivew 버그 발생

.github/workflows/deploy.yml, README.md, src/main/resources/application.yaml, src/main/resources/logback-spring.xml
- resolve #82 
- 이전에 작성한 #81 을 보충합니다.
<br>
- `profile` 을 분리하였습니다.
- 이제 개발환경에서는 `develop` 프로파일을 적용해주세요.
- 스프링부트 기본 로그와 비슷한 형태로 로그 출력형태를 수정하고, 색깔을 추가했습니다.
- 운영 환경에서만 `Sentry` 의 `appender` 를 적용하도록 하였습니다.
- 리드미에 서비스 아키텍처를 첨부하였습니다.
<br>
- 로컬에서 환경변수 `ACTIVE_PROFILE` 을 `develop` 로 적용해주세요!                       
<br>
=> [SETTING] 운영 환경과 개발 환경 설정 분리

.github/workflows/deploy.yml, build.gradle, src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java, src/main/java/com/yju/toonovel/global/aws/controller/AwsController.java, src/main/java/com/yju/toonovel/global/aws/service/S3Service.java, src/main/java/com/yju/toonovel/global/config/AwsConfig.java, src/main/java/com/yju/toonovel/global/config/SecurityConfig.java, src/main/resources/application.yaml
- resolve #52 
- PreSignedUrl을 발급하는 방식으로 구현하였습니다.
- ElasticLoadBalancer에서 사용할 헬스 체크 엔드포인트를 추가하였습니다.
<br>
- `MultipartFile`로 파일을 직접 받아 업로드하는 방식이 아니라, 백엔드에서는 `PreSignedUrl`만 발급해주고, 프론트에서 실제 파일을 업로드하는 방식으로 구현하였습니다.
- 현재 해당 API는 Security에서 임시로 USER만 가능하도록 권한 설정하였으나 추후에 API들 권한 설정할 때 자세하게 설정하도록 하겠습니다.
- `ELB` 에서 헬스 체크 하는 API 엔드포인트를 만들었습니다.
- 이전에는 `api/v1/novel` 로 체크하고 있었는데.. 의미 없는 트랜잭션이 발생하는 것 같았습니다.
- 단순히 정상 작동 시 `200` 코드를 반환해줄 수 있는 엔드포인트입니다.
<br>
- [AWS - PreSignedUrl](https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/userguide/PresignedUrlUploadObject.html)
- [참고한 블로그 - AWS Presigned URL](https://velog.io/@hwaya2828/AWS-Presigned-URL)
- 궁금한 부분 있으시면 코멘트 주세요!                  
<br>
=> [FEAT] S3 이미지 업로드 기능 구현

src/main/java/com/yju/toonovel/global/security/jwt/controller/TokenController.java, src/main/java/com/yju/toonovel/global/security/jwt/service/TokenService.java, src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/yju/toonovel/global/util/CookieUtils.java
- resolve #97 
- 리프레쉬 토큰 정책 수정
<br>
- `api/v1/token`  post 요청이 들어오는 재발급 요청에 대해서 쿠키의 값을 추출합니다.
- FE에서 리프레쉬 토큰을 추출하여 헤더에 담을 필요 없이 그냥 요청하시면 됩니다.
- 토큰 발급 시 httpOnly 옵션을 설정하였습니다.
- `api/v1/token` delete 요청으로 로그아웃 API 를 추가하였습니다.
- `httpOnly` 옵션의 쿠키를 빈 쿠키를 발급하여 덮어 씌웁니다.
- 액세스 토큰은 별도로 처리하지 않았습니다. 필요 시 프론트에서 지워주시면 될 것 같습니다.
<br>
- 이전에 이해도가 모자라서 빈틈이 많았던 로직입니다.
- 액세스 토큰도 이후에는 굳이 쿠키에 담아서 전송하지 않고, 쿼리 스트링이나 바디에 담아주는 식으로 변경할 수 있을 것 같습니다.
- 현재는 변동없이 쿠키에 담아서 전송하고 있습니다.
- 리프레쉬 토큰은 `httpOnly` 쿠키로 발급합니다.
<br>
=> [REFACTOR] 리프레쉬 토큰 로직 수정

src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java, src/main/java/com/yju/toonovel/domain/post/dto/PostAllResponseDto.java, src/main/java/com/yju/toonovel/domain/post/dto/PostResponseDto.java, src/main/java/com/yju/toonovel/domain/post/entity/Post.java, src/main/java/com/yju/toonovel/domain/post/service/PostService.java, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/dto/UserMyProfileResponseDto.java, src/main/java/com/yju/toonovel/domain/user/dto/UserProfileUpdateRequestDto.java, src/main/java/com/yju/toonovel/domain/user/entity/User.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java, src/main/java/com/yju/toonovel/global/common/Sort.java
- resolve #95 
- 요구 사항 변경에 따른 간단한 추가 작업
<br>
- `User`
- 유저 정보 업데이트 API 분리 및 추가
- 이전에 회원가입 -> 추가정보 입력에서 사용되는 API의 경로가 `api/v1/user/join`으로 변경되었습니다.
- 마이페이지 - 프로필 수정에서 사용되는 API를 추가하고, 경로를 `api/v1/user/me`로 하였습니다.
- 유저 정보 반환 Dto 분리
- 내 프로필 조회와 타인 프로필 조회 시 반환되는 Dto를 분리하였습니다.
- `AuthorNotFoundException` 이 던져지지 않는 것을 발견하여 수정하였습니다.
- `Novel`
- 좋아요 수, 리뷰 수 순으로 조회하는 기능을 추가하였습니다.
- 전체, 상세 조회 시 리뷰 수, 좋아요 수도 반환하도록 하였습니다.
- `Post` 
- 누락 작품 신청 카테고리 : 이미 존재하는 건의가 그 역할을 할 수 있을 것 같아서 그대로 두었습니다.
- 전체, 상세 조회 시 댓글 수를 반환하도록 하였습니다.
<br>
- 전체적으로 리팩터링이 필요하다고 느꼈습니다. 다만 당장에 수정하지는 않았습니다.
- 초기에 작성한 코드와 이후에 작성한 코드가 스타일이 많이 다른 것을 인지했습니다.
- 정적 팩토리 메소드나 빌더 패턴 등을 사용하여 좀 더 깔끔하게 작성 가능한 부분이 많이 보였습니다.
- 이후에 기간을 충분히 잡고 함께 고쳐보는게 좋을 것 같습니다.
- **수정할 부분이나,  더 추가할 부분 있으면 말씀해주시면 빠르게 반영하겠습니다!**
<br>
=> [FEAT] 간단한 기능 추가 (정보 수정, 조회 기준 추가 등)

src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java, src/main/java/com/yju/toonovel/domain/user/controller/UserController.java, src/main/java/com/yju/toonovel/domain/user/dto/AuthorListPaginationRequestDto.java, src/main/java/com/yju/toonovel/domain/user/dto/AuthorListResponseDto.java, src/main/java/com/yju/toonovel/domain/user/repository/ChatRoomCustomRepository.java, src/main/java/com/yju/toonovel/domain/user/repository/ChatRoomCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepository.java, src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #108 
<br>
- 최신작가 리스트 조회 - 가장 최근 승인이 된 작가
- _인기리뷰 - 이미 존재하는 API_
- 인기 채팅방 - 가입된 회원 수가 가장 많은 채팅방
- 작가 검색 기능 - `nickname` 검색으로 지원
<br>
- 어떤 도메인에서 작업해야할지 많이 고민했습니다.
- (현재는 권한 설정이 없지만) `chatting` 도메인은 접근 권한 설정이 있는 것이 어울린다고 생각합니다
- 현재 기능은 특별한 목적이라기보단, 페이지를 채우기 위한 기능에 가까우며, `chatting` 도메인은 메신저 기능과 밀접한 연관이 있는 기능만 있으면 좋겠다 느꼈습니다.
- 기능의 이름? 목적?과는 별개로 실제 반환값은 작가의 정보입니다.
- 위와 같은 이유로 `user` 도메인에 작성하였습니다
- `novel` 도메인을 봤는데 최대한 많은 데이터를 보내주고 있더군요. 하지만 `user`의 정보는 민감할 수 있기 때문에, 최소한의 데이터만 보내주는 식으로 작업했습니다.
<br>
=> [FEAT] API 기능 보충 (최신작가, 인기리뷰, 인기채팅룸)

src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java, src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java
- resolve #111 
> 작가의 userId로 채팅방에 가입할 수 있는 API
기존 채팅방의 roomId로 가입하는 기능은 있지만, https://github.com/TooNovel/TooNovel-BE/pull/110 에서 필요성이 생겼습니다
<br>
- 작가의 `userId`로 채팅방에 가입하는 API
<br>
- 이로 인해 채팅방에 가입하는 API가 2개가 되었습니다(채팅방의 `roomId`, 작가의 `userId`). 리팩토링의 필요성이 보이긴 하지만 당장 급한 일 먼저 처리하겠습니다.. 😢 
<br>
=> [FEAT] 작가 ID로 채팅방 가입하는 기능

src/main/java/com/yju/toonovel/domain/admin/service/AdminService.java, src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java, src/main/java/com/yju/toonovel/domain/user/dto/UserProfileUpdateRequestDto.java, src/main/java/com/yju/toonovel/domain/user/entity/User.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java, src/main/java/com/yju/toonovel/global/aws/controller/AwsController.java, src/main/java/com/yju/toonovel/global/aws/service/S3Service.java
- resolve #109 
<br>
- 요구사항 변경에 따른 API 수정
- 마이페이지 - 프로필 수정 시 성별과 생년월일을 더 이상 받지 않음
- 프로필 이미지 이름을 UUID로 생성
- `/api/v1/aws/s3` 에서 더 이상 `filename`을 받지 않습니다.
- 변경에 따른 사용되지 않는 import문 삭제
- 던져지지 않는 예외를 발견하여 수정하였습니다.
<br>
- #103 이전에 말씀하신대로 API를 변경하였습니다.
<br>
=> [REFACTOR] 유저 프로필 수정 API 수정

src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ReplyDto.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepository.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepository.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java, src/main/java/com/yju/toonovel/domain/chatting/service/ChatService.java
- resolve #119
> 작가가 독자의 메세지 보낸 답장인 Reply 조회 기능 추가
<br>
- 채팅 조회 방식 변경 `최근 30개` -> `일자별 조회`
- ex) `date=2023-06-18`을 쿼리스트링으로 전달하면 해당 날짜의 채팅(답장)이 조회되는 방식
- `ChatDto`, `ReplyDto`에 작성 시간 추가 - DB 입력 시간 기준
- Reply 조회 기능 추가
<br>
- 프론트엔드에서는 채팅을 조회하기 위하여 Chat 조회 요청과, Reply 조회 요청을 따로 해야하도록 구성하였습니다.
- 이렇게 구성한 이유는 데이터 형식이 다르므로 하나의 요청으로 처리할 경우 백엔드, 프론트엔드 모두 취급 난이도가 상승하기 때문입니다.
- 현재 n+1 문제는 없는 것으로 보이지만, 채팅 조회 한번에 2번이나 요청이 이루어지는 구조상 쿼리 횟수가 많습니다. 추후에 개선을 시도하도록 하겠습니다
<br>
=> [FEAT] Reply 조회 기능 추가

src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/user/dto/AuthorListResponseDto.java, src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #126
> 작가 검색 시 무한 스크롤이 비정상적인 현상
- resolve #129 
> 채팅방 처음 접속 시 이전 채팅, 답장 조회 API 변경
<br>
- 프론트엔드에서 검색 기준을 잡을 수 있도록 응답 dto에 `enrollId` 추가
- 조회 일자를 null로 전송하면 최근 7일간의 채팅/답장 반환
<br>
=> [BUG] [REFACTOR] 작가 검색 시 무한 스크롤 문제, 채팅방 처음 조회 시 API 변경

src/main/java/com/yju/toonovel/domain/admin/dto/EnrollListResponseDto.java, src/main/java/com/yju/toonovel/domain/admin/entity/EnrollHistory.java, src/main/java/com/yju/toonovel/domain/admin/repository/AdminRepositoryImpl.java, src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticsRepository.java, src/main/java/com/yju/toonovel/domain/statistics/service/StatisticsService.java, src/main/java/com/yju/toonovel/domain/user/service/UserService.java
- resolve #128 
<br>
- 작가 신청 승인 시 버그 발생
- 회원가입 시 입력한 닉네임, 작가 신청할 때 입력한 닉네임 다를 경우 버그 발생
- 이유는 기존 코드는 회원가입시 입력한 유저의 닉네임을 사용하고 있었기 때문이었습니다.
- `enrollHistory` 테이블에 `nickname` 컬럼을 추가하였습니다.
- 내 작품 통계 조회 시 버그 발생
- 이 버그 또한 회원가입시 입력한 닉네임과 `novel` 테이블의 `author` 칼럼과 비교하려 했기 때문에 버그가 발생했습니다.
- 해결은 닉네임으로 조회하는것이 아닌 작가 승인이 되었을 때 `novel` 테이블에 업데이트된 userId와 `user`테이블의 `userId`를 조회하는 것으로 해결했습니다.
<br>
- `enrollHistory` 테이블에 `nickname` 컬럼이 추가되었습니다.                             
<br>
=> [BUG] 작가 통계 조회 버그 발생

src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomResponseDto.java, src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRoomRepository.java
- resolve #138 
> 채팅방 조회 dto 수정
<br>
- 요구사항이 바뀜에 따라 유저 비교용 userId 값 반환
- 기존에는 닉네임이 unique여서 userId가 없어도 됐지만, 닉네임이 unique가 아니게 되었으므로 비교용 userId 반환
<br>
=> [FEAT] 채팅방 조회 Dto 수정

src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java, src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java, src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java, src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
- resolve #140 
- Sort 기준이 추가되고 나서, 커서를 추가 했어야 하는데 하지 않아서 발생한 오류입니다.
<br>
- `Novel`
- `grade`가 Null이 아닌 0을 반환하도록 쿼리를 수정하였습니다.
- `RequestDto` 에 좋아요 수, 리뷰 수, 평점, 소설 추가 일자를 추가 하였습니다.
- 원하는 정렬 기준에 해당하는 값을 보내면 됩니다.
- ex) 좋아요 순 정렬일 때는 마지막 작품의 `novelId, grade`, `Sort`
- ex) 최신 정렬일 때는 마지막 작품의 `novelId, createdDate`, `Sort`
- 이제 들어온 값에 따라 올바르게 정렬하여 조회가 가능합니다.
- 기존에는 novelId로만 페이징을 하였는데, 이제는 정렬 기준으로 사용할 값도 같이 사용합니다.
<br>
- no-offset 방식이 적용된 기능에는 이와 같은 수정이 필요합니다.
- 코드가 꽤나 변경되어서 프론트도 수정이 좀 필요합니다.
- 궁금한 부분 있으면 질문해주세요!                   
<br>
=> [BUG] no-offset 페이징 관련 버그

src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java, src/main/java/com/yju/toonovel/domain/novel/exception/NovelRecommendationNotExistException.java, src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java, src/main/java/com/yju/toonovel/global/config/RestTemplateConfig.java, src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
- resolve #145 
- `Recommend` 기능을 `Novel` 도메인으로 이동시키고, 리팩터링
<br>
- 더 이상 `Recommend` 도메인을 사용하지 않습니다.
- 필요 없다고 판단되는 모델 수동 업데이트 API를 제거할 예정입니다.
- 추천 API를 `Novel` 도메인으로 이동시킵니다.
- 버저닝이 애매하기는 판단하여, 프론트엔드 수정이 끝나면 해당 도메인을 삭제 처리 하겠습니다.
- `Novel` 도메인에서 추천 기능을 맡습니다.
- `api/v1/novel/recommend` 로 API 경로 변경이 필요합니다.
- RestTemplate를 주입 받아서 사용합니다.
- `connectTimeout`, `readTimeout` 을 설정하였습니다.
- FastAPI에서 반환하는 에러에 대해서 예외 처리를 추가하였습니다.
<br>
- `Recommend` 도메인을 그대로 남겨두고, 사용하는 방법도 고려했습니다.
'Service 레이어간의 의존도가 높아지는 게 아닌가?' 하는 고민을 하면서 여러 가지 방법을 생각했었습니다.
`Controller` 에서 필요한 서비스를 모두 호출하는 방법, 상위 `Service` 를 만드는 방법,, 여러가지를 고민했는데, 현재로서는 `Novel` 도메인에 책임을 맡기고, 필요가 없어진 `Recommend` 도메인을 삭제하는 게 제일 좋다고 생각했습니다.
- `Recommend` 도메인은 프론트 수정이 끝나면 제거 하겠습니다.
- 의견 있으시면 남겨주세요!
<br>
=> [REFACTOR] Recommend 도메인 리팩터링

src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomCreateRequestDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomResponseDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/FilterChatRequestDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/FilterChatResponseDto.java, src/main/java/com/yju/toonovel/domain/chatting/dto/ReplyDto.java, src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java, src/main/java/com/yju/toonovel/domain/chatting/service/ChatService.java
- resolve #151
> Chatting 도메인 중 팀에서 정한 규칙과 맞지 않은 부분 수정
<br>
- Service, Controller
- `get~~` 와 같은 메서드명을 `find~~`로 통일
- 다른 클래스에서 사용되지 않는 메서드의 접근제어자를 `public`으로 변경
- Dto
- 객체 생성 방식을 정적 팩토리 메소드로 통일
- 따라서, 다른 클래스에서 사용되지 않는 Builder 패턴 생성자를 `private`으로 변경
- Valiation 적용
- `final` 키워드 적용
<br>
- `ChatCustomRepositoryImpl`의 코드 중에
```
@Override
public List<Chat> findAllByChatRoomToAuthor(ChatRoom chatRoom) {
return jpaQueryFactory
.selectFrom(chat)
.where(
chat.chatRoom.eq(chatRoom),
chat.createdDate.between(
LocalDate.now().minusDays(7).atStartOfDay(), LocalDate.now().plusDays(1).atStartOfDay()
)
)
.orderBy(chat.chatId.desc())
.fetch();
}
@Override
public List<Chat> findAllByChatRoomAndDateToAuthor(ChatRoom chatRoom, LocalDate date) {
return jpaQueryFactory
.selectFrom(chat)
.where( …
```
=> [REFACTOR] Chatting 도메인 리팩토링
