.editorconfig
.github/workflows/checkstyle.yml
build.gradle
config/checkstyle/naver-checkstyle-rules.xml
config/checkstyle/naver-checkstyle-suppressions.xml
config/checkstyle/naver-intellij-formatter.xml

- resolve #3 
- naver convention 적용
<br>
- `.editorconfig` 파일 추가
-  `config/checkstyle` 경로에 컨벤션, 포매터 xml 추가
- `build.gradle` checkstyle 플러그인 추가
- `.github/workflows` 경로에 `checkstyle.yml` workflow 작성
<br>
- 노션 문서 확인하시고 IDE 에도 적용 바랍니다.                           
<br>

[SETTING] CheckStyle 적용

---

src/main/java/com/yju/toonovel/domain/post/entity/Post.java

- resolve #11 
- 글쓰기 진행 시 DB에 null값이 들어가는 현상 해결
<br>
- @DynamicInsert 주석을 제거하여 SQL문에 null 값이 명시적으로 포함되어 null값이 삽입되었던 문제였습니다.
- @DynamicInsert 주석을 다시 추가하여 해결했습니다.
<br>
- DynamicInsert에 관한 내용은 23135d1 에서 확인할 수 있습니다
- DynamicInsert와 같이 제거했던 DynamicUpdate는 아래 글을 참고하여 다시 추가하지 않는 것으로 결정하였습니다
- https://www.baeldung.com/spring-data-jpa-dynamicupdate#entityWithDA
<br>

:bug: @ColumnDefault("0")이 적용되지 않는 문제 해결

---

src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java

- resolve 
- 사용자에게 토큰 발급
- 토큰 인증을 통한 회원 가입
<br>
- 필요한 추가 정보를 받기 위해 회원 가입을 할 때 토큰 인증을 통해 추가 정보 회원 가입 할 수 있도록 변경
- 회원 가입 시 header에 토큰을 담아 보내주는 방식에서 cookie에 토큰을 담아 보내주는 방식으로 변경
<br>
- 이 코드에서는 determineTargetUrl 없이 바로 URL에 redirect했는데 추후에 이 메서드를 사용할지 결정해야 할 것 같습니다.               
- SuccessHandler 에서 addHeader부분 일단 다 제거 했는데 혹여나 실수한 부분이 있는지 체크 부탁드립니다. 
<br>

[REFACTOR] 토큰 전달 방식 변경 및 회원 가입 기능 추가

---

src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java

- resolve #25 
<br>
- @NoArgsConstructor 제거
<br>

[BUG] 검색 조회 Dto 수정

---

src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java

- resolve #30 
<br>
- ReviewRepositoryImpl
- 전체개수 카운트 안되는 버그 수정
- ReviewController
- 페이징 처리 위해 시작페이지 받는 것으로 수정
<br>

:bug: Review 도메인 수정

---

src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java

- resolve #39 
<br>
- 중복된 코드를 reviewSelect 메서드로 변경
<br>

:recycle: Review 도메인 일부 수정

---

README.md

- resolve #47 
- 리드미 초안 작성
<br>
- 배포 이후에 남은 내용 채우고 지속적으로 수정하도록 하겠습니다.
<br>

[SETTING] Readme 초안 작성

---

src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java

- resolve #49 
- Review 전체 조회 시 발생하는 문제 수정
<br>
- 초기값 null에 대응하지 못하는 문제 -> int를 Integer로 바꾼 뒤 null 체크 로직 추가
- sort의 기본값이 비정상적인 문제 -> sort를 Sort로 변경
<br>

:bug: Review Paging 기능 수정

---

src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java
src/main/java/com/yju/toonovel/domain/comment/dto/CommentAllResponseDto.java
src/main/java/com/yju/toonovel/domain/comment/dto/CommentPaginationRequestDto.java
src/main/java/com/yju/toonovel/domain/comment/dto/CommentRegisterRequestDto.java
src/main/java/com/yju/toonovel/domain/comment/dto/CommentUpdateRequestDto.java
src/main/java/com/yju/toonovel/domain/comment/entity/Comment.java
src/main/java/com/yju/toonovel/domain/comment/entity/LikeComment.java
src/main/java/com/yju/toonovel/domain/comment/exception/CommentAlreadyLikedException.java
src/main/java/com/yju/toonovel/domain/comment/exception/CommentNotFoundException.java
src/main/java/com/yju/toonovel/domain/comment/exception/CommentNotMatchUserException.java
src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepository.java
src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepositoryCustom.java
src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/comment/repository/LikeCommentRepository.java
src/main/java/com/yju/toonovel/domain/comment/service/CommentService.java
src/main/java/com/yju/toonovel/domain/comment/service/LikeCommentService.java
src/main/java/com/yju/toonovel/domain/post/exception/PostNotFoundException.java
src/main/java/com/yju/toonovel/domain/post/repository/PostRepository.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java

- resolve #21 
- Comment 도메인 기능 구현
<br>
- Comment 관련 기능
- 댓글 작성, 수정, 삭제
- 하나의 게시글에 있는 모든 댓글 조회
- 댓글 좋아요
- 한번 좋아요 하면, 이미 좋아요 했습니다 라는 예외 반환
- 숫자 페이징 구현
- sort enum클래스 사용해 정렬 기능 구현
- 관련 예외 추가
-CommentAlreadyLikedException 
-CommentNotFoundException 
-CommentNotMatchUserException 
-PostNotFoundException 
- Review 도메인 리팩토링
- ReviewRepositoryImpl 내의 불필요한 메서드 제거
- 불필요한 주석 제거
<br>
- 부족한 점 말씀해주시면 고치도록 하겠습니다.                         
<br>

[FEAT] Comment 도메인 기능 구현

---

src/main/java/com/yju/toonovel/domain/review/dto/AllReviewInWorkResponseDto.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java

- resolve #53 
<br>
- 한 작품에 대한 리뷰 조회 시 넘겨주는 AllReviewInWorkResponseDto 에 review_id 추가
- 쿼리 문도 review_id 조회 할 수 있도록 수정
<br>

[BUG] Review 조회 시 발생하는 버그

---

src/main/java/com/yju/toonovel/domain/review/dto/ReviewByNovelResponseDto.java

- resolve #67 
<br>
- ReviewByNovelResponseDto
- reviewContent누락 -> 추가
<br>

[BUG] review 조회 버그 발생

---

.github/workflows/checkstyle.yml
.github/workflows/deploy.yml
appspec.yml
build.gradle
src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java

- resolve #69 
- 배포 자동화
<br>
- `GithubAction` + `CodeDeploy` 를 이용한 자동 배포
- `Issue`에 후술하겠습니다.
- `checkStyle` 트리거 변경
- PR시 작동
- 회원 가입 후 `redirect url` 변경
- 현재 배포된 프론트엔드 url로 변경하였습니다.
<br>
- 작동 확인 후 `Issue` 에 상세 설명 하겠습니다.                             
<br>

[SETTING] AWS 배포 준비

---

src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
src/main/java/com/yju/toonovel/global/config/WebConfig.java

- resolve #71 
<br>
- countQuery 메서드 수정
- count할때에 where이 들어가야 해당 사용자가 쓴 리뷰의 개수를 가져올 수 있는데 빠져있어서 추가하였습니다.
- eqUserId를 사용해 전체조회시에는 null을 주어 전체조회 하였습니다. 
<br>

[BUG] Review 조회 버그

---

.github/workflows/checkstyle.yml
.github/workflows/deploy.yml
build.gradle
src/main/resources/application.yaml
src/main/resources/logback-spring.xml

- resolve #80 
- Sentry 도입, logback 우선 작성
<br>
- Sentry 관련 의존성 추가
- logback 관련 설정 작성
<br>
- 리뷰어에게 할 이야기가 있다면 적어주세요.                              
<br>

[SETTING] logback 추가 및 모니터링 도입

---

src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/dto/PlatformResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java

- resolve #86 
- 소설 상세 조회 기능 변경
<br>
- 이전에는 각 소설의 플랫폼 url이 없었는데, db에 추가하면서 같이 반환 되도록 수정하였습니다.
<br>
- 이번주도 파이팅..                       
<br>

[REFACTOR] 소설 상세 조회 기능 수정

---

src/main/java/com/yju/toonovel/domain/post/controller/PostController.java
src/main/java/com/yju/toonovel/domain/post/dto/PostAllResponseDto.java
src/main/java/com/yju/toonovel/domain/post/dto/PostResponseDto.java
src/main/java/com/yju/toonovel/domain/post/dto/UserLikeCheckPostResponseDto.java
src/main/java/com/yju/toonovel/domain/post/repository/LikePostRepository.java
src/main/java/com/yju/toonovel/domain/post/repository/PostRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/post/service/LikePostService.java
src/main/java/com/yju/toonovel/domain/post/service/PostService.java

- resolve #88 
<br>
- 게시글에 전체 조회시 카테고리에 대한 페이징이 전체 게시글에 대한 페이지 수로 되어있어 수정
- 게시글에 대한 좋아요 시 좋아요 한 상태인지 체크 요청
- 게시글 전체 조회시 유저에 대한 정보가 없어 유저 닉네임 추가
<br>

[REFACTOR] 게시글 도메인 일부 수정

---

.github/workflows/deploy.yml
build.gradle
src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
src/main/resources/application.yaml
src/main/resources/logback-spring.xml

- resolve #89 
- CloudWatch에서도 로그를 관리하도록 하겠습니다.
<br>
- AWS 키를 여럿 사용하고 있었는데 불필요한 것 같아서 일부 통합합니다.
- CloudWatch 관련 로그 설정
- S3관련 의존성 변경
- 기존에 사용하던 [org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-aws/2.2.6.RELEASE)에 취약점이 존재해서 라이브러리를 변경합니다.
- 관련 내용 : https://devhub.checkmarx.com/cve-details/CVE-2022-31159/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea
<br>
- 이번 주도 파이팅..!                   
<br>

[FEAT] CloudWatch 연결

---

src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java

- resolve #99 
<br>
- `findNovelByAuthor` 메서드에 스크롤 페이징시 마지막으로 넘어온 novelId에 대한 조건 추가
<br>

[BUG] 내 작품 조회 버그

---

src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
src/main/java/com/yju/toonovel/domain/chatting/dto/ReplyDto.java
src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRoomRepository.java

- resolve #105 
<br>
- repository에 `@Param` 추가
- Dto에 `@NoArgsConstructor` 추가
<br>
- `@Param`, `@NoArgsConstructor` 모두 명시되어 있는 것이 정상적인 코드이기에, 라이브러리쪽을 해결하기 보다는 해당 어노테이션을 명시하는 것으로 해결했습니다
- _일단 수정은 했지만, 명확한 원인은 확인 중입니다.._
<br>

[BUG] 실행 환경에 따라 메신저가 작동하지 않는 문제

---

src/main/java/com/yju/toonovel/domain/review/dto/ReviewByUserResponseDto.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java

- resolve #113 
- 리뷰 전체 조회 API 수정
<br>
- Response Dto 에 `novelId`를 추가하고, `projection` 수정
<br>
- 또 수정 필요한 부분 있으시면 말씀해주세용                            
<br>

[REFACTOR] 리뷰 조회 API 수정

---

src/main/java/com/yju/toonovel/domain/post/repository/PostRepositoryImpl.java
src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/yju/toonovel/global/util/CookieUtils.java

- resolve #116 
- resolve #117 
- 쿠키 옵션에 도메인 설정, Post 전체 조회 시 댓글 수 정상적으로 반환하도록 수정
<br>
- 이후에 적음
<br>
- Post 관련해서는 좀 더 테스트를 해봤어야 하는데, 꼼꼼하지 못했던 점 죄송합니다..                         
<br>

[BUG] 배포 환경에서 쿠키가 전달되지 않는 문제, Post 전체 조회 관련 문제

---

scripts/gh_deploy.sh

- resolve #121 
- 배포 스크립트 수정
<br>
- `sudo kill -15`로 변경 `sleep 5` 추가
<br>
- 이전에 간헐적으로 인스턴스가 죽던 현상의 원인으로 추측됩니다.                           
<br>

[BUG] 배포 스크립트 수정

---

src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRepository.java
src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyRepository.java
src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java

- resolve #123 
> 채팅방이 정상적으로 삭제되지 않는 현상
- ChatDto에 필터링 여부 반환
<br>
- `ChatRoom` 엔티티에 `cascade` 옵션이 없어 삭제가 안되던 현상을 해결하기 위해 `chatRoomId`로 채팅, 리플을 삭제하는 것으로 해결
- ChatDto에 필터링 여부를 `ok` 혹은 `bad`로 반환
<br>

[BUG] 채팅방 삭제 버그, ChatDto 리턴값 추가

---

src/main/java/com/yju/toonovel/domain/admin/repository/EnrollRepository.java
src/main/java/com/yju/toonovel/domain/user/exception/AlreadyAuthorEnrollException.java
src/main/java/com/yju/toonovel/domain/user/service/UserService.java
src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java

- resolve #125 
<br>
- 이미 작가신청이 되었을 경우의 예외 추가
<br>

[BUG] 작가 신청 버그 발생

---

src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java

- resolve #136 
<br>
- 내가 좋아요 한 작품 조회시 넘어오지 않던 리뷰개수, 좋아요 개수를 dto에 추가했습니다.
<br>

[BUG] 좋아요 한 작품 조회시 필요한 데이터 넘어오지 않는 버그

---

src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java
src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/dto/PlatformResponseDto.java
src/main/java/com/yju/toonovel/domain/novel/repository/NovelRepository.java
src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java

- resolve #143 
- `Novel` 도메인 코드를 전체적으로 정리하였습니다.
<br>
- DTO
- 정적 팩토리 메서드를 사용하고, 일반적으로 기본 생성자에 접근할 수 없도록 처리하였습니다.
- `final` 키워드를 추가해 불변성을 보장하였습니다.
- Controller, Service
- `findAll`, `findById` 등 조금 모호하다 느껴지는 메서드 명을 명확하게 변경하였습니다.
- 그 외 불필요한 주석을 발견하여 제거하였습니다.
<br>
- 추가적인 아이디어 있으면 말씀해주세요! 이 다음으로는 recommend 도메인 작업하겠습니다.                  
<br>

[REFACTOR] Novel 도메인 리팩터링

---

src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
src/main/java/com/yju/toonovel/domain/review/dto/ReviewByNovelResponseDto.java
src/main/java/com/yju/toonovel/domain/review/dto/ReviewByUserResponseDto.java
src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java
src/main/java/com/yju/toonovel/domain/review/dto/ReviewRegisterRequestDto.java
src/main/java/com/yju/toonovel/domain/review/entity/LikeReview.java
src/main/java/com/yju/toonovel/domain/review/entity/Review.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewCustomRepository.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java
src/main/java/com/yju/toonovel/domain/review/service/LikeReviewService.java
src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java

- resolve #147 
- `Review` 도메인 전체적인 리팩터링 입니다.
<br>
- Repository
- QueryDsl Repository : 통일된 네이밍으로 수정하였습니다.
- 필요없는 메서드 제거 하였습니다.
- Service, Controller
- 메서드 이름 수정하였습니다.
- Dto
- final 키워드를 추가하였습니다.
- dtoToEntity를 제거하고 entity에 정적 팩터리 메서드를 추가하였습니다.
<br>
- 혹시나 제가 놓친 부분 있다면 말씀해주시면 감사하겠습니다.                         
<br>

[REFACTOR] Review 도메인 리팩터링

---

src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
src/main/java/com/yju/toonovel/domain/user/dto/AuthorListPaginationRequestDto.java
src/main/java/com/yju/toonovel/domain/user/dto/AuthorListResponseDto.java
src/main/java/com/yju/toonovel/domain/user/dto/AuthorRegisterRequestDto.java
src/main/java/com/yju/toonovel/domain/user/dto/UserMyProfileResponseDto.java
src/main/java/com/yju/toonovel/domain/user/dto/UserProfileResponseDto.java
src/main/java/com/yju/toonovel/domain/user/dto/UserProfileUpdateRequestDto.java
src/main/java/com/yju/toonovel/domain/user/dto/UserRegisterRequestDto.java
src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/user/service/UserService.java

- resolve #153 
- `User` 도메인 리팩터링
<br>
- Service, Controller
- 메서드 이름과 파라미터의 이름을 좀 더 적절하게 수정
- 불필요한 코드 제거
- DTO
- 불필요한 코드 제거
- 정적 팩토리 메소드 적용
- 프로젝션으로 조회하는 DTO는 X
- final 키워드 적용
<br>
-  의견 있으시면 남겨주세요!        
<br>

[REFACTOR] User도메인 리팩터링

---

src/main/java/com/yju/toonovel/domain/admin/controller/AdminController.java
src/main/java/com/yju/toonovel/domain/statistics/controller/StatisticsController.java
src/main/java/com/yju/toonovel/domain/statistics/dto/AdminStatisticsResponseDto.java
src/main/java/com/yju/toonovel/domain/statistics/dto/StatisticsResultResponseDto.java
src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticCustomRepository.java
src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticCustomRepositoryImpl.java
src/main/java/com/yju/toonovel/domain/statistics/service/StatisticsService.java

- resolve #149 
- `Statistics` 도메인 리팩토링 입니다.
<br>
- Service, Controller
- 메서드 이름 변경
- Dto
- 사용하지 않는 어노테이션 삭제
- Repository
- QueryDsl Repository 네이밍 통일
<br>
- 다른 도메인에 비해 패키지가 적어 변경한 내용이 별로 없습니다. 그래도 혹시나 놓친 부분 있을 수 있어 말씀해주시면 바로 고치도록 하겠습니다.   
- Service의 통계자료 조회 메서드는 find보다는 get이 어울릴 것 같아 get~~으로 사용했습니다.                   
<br>

[REFACTOR] Statistics 도메인 리팩터링
